# 运行模式offline / online （如果使用offline离线模式运行不支持AI分析，同时需要把巡检命令拉到本地的/utils/offline_commands.json文件中）
run_mode=offline
# 是否允许上传巡检报告用于分析（默认不允许）
upload_report=False
# 社区版本云端接口，用于获取巡检命令、AI分析提示词等。若您允许上传巡检报告用于AI模型改进分析，将会通过此接口回传（该功能需要配置为允许上传（默认不允许））
community_api = https://api-community-sunchha.bytesycn.cn/api/v1
# 用户代理，用于在请求中标识客户端
user_agent=Sunchha_Community/1.0.0
# 阿里百炼平台API地址
ai_base_url=https://dashscope.aliyuncs.com/compatible-mode/v1
# 阿里百炼平台支持的模型，默认使用qwen3-max
ai_model=qwen3-max
# 阿里百炼平台API密钥，需要在阿里百炼平台申请
ai_api_key=
